-- SPDX-License-Identifier: Apache-2.0
-- Licensed to the Ed-Fi Alliance under one or more agreements.
-- The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
-- See the LICENSE and NOTICES files in the project root for more information.

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AbsenceEventCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AcademicHonorCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AcademicSubjectDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AcademicWeek_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AccommodationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Account_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AccountabilityRating_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AccountClassificationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AccountCode_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AchievementCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Actual_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AdditionalCreditTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AddressTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AdministrationEnvironmentDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AdministrativeFundingControlDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Assessment_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AssessmentCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AssessmentIdentificationSystemDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AssessmentItem_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AssessmentItemCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AssessmentItemResultDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AssessmentPeriodDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AssessmentReportingMethodDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AttemptStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_AttendanceEventCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_BehaviorDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_BellSchedule_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Budget_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Calendar_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CalendarDate_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CalendarEventDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CalendarTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CareerPathwayDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CharterApprovalAgencyTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CharterStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CitizenshipStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ClassPeriod_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ClassroomPositionDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Cohort_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CohortScopeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CohortTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CohortYearTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CommunityOrganization_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CommunityProvider_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CommunityProviderLicense_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CompetencyLevelDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CompetencyObjective_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ContactTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ContentClassDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ContinuationOfServicesReasonDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ContractedStaff_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CostRateDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CountryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Course_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseAttemptResultDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseDefinedByDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseGPAApplicabilityDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseIdentificationSystemDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseLevelCharacteristicDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseOffering_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseRepeatCodeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CourseTranscript_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Credential_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CredentialFieldDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CredentialTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CreditTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CTEProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_CurriculumUsedDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DeliveryMethodDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Descriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DiagnosisDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DiplomaLevelDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DiplomaTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisabilityDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisabilityDesignationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisabilityDeterminationSourceTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisciplineAction_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisciplineActionLengthDifferenceReasonDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisciplineDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisciplineIncident_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_DisciplineIncidentParticipationCodeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationalEnvironmentDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationContent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationOrganization_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationOrganizationCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationOrganizationIdentificationSystemDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationOrganizationInterventionPrescriptionAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationOrganizationNetwork_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationOrganizationNetworkAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationOrganizationPeerAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationPlanDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EducationServiceCenter_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ElectronicMailTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EmploymentStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EntryGradeLevelReasonDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EntryTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_EventCircumstanceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ExitWithdrawTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_FeederSchoolAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GeneralStudentProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Grade_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GradebookEntry_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GradebookEntryTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GradeLevelDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GradeTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GradingPeriod_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GradingPeriodDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GraduationPlan_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GraduationPlanTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_GunFreeSchoolsActReportingStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_HomelessPrimaryNighttimeResidenceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_HomelessProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_IdentificationDocumentUseDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_IncidentLocationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_InstitutionTelephoneNumberTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_InteractivityStyleDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_InternetAccessDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Intervention_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_InterventionClassDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_InterventionEffectivenessRatingDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_InterventionPrescription_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_InterventionStudy_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LanguageDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LanguageInstructionProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LanguageUseDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LearningObjective_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LearningStandard_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LearningStandardCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LearningStandardEquivalenceAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LearningStandardEquivalenceStrengthDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LearningStandardScopeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LevelOfEducationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LicenseStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LicenseTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LimitedEnglishProficiencyDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LocaleDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LocalEducationAgency_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_LocalEducationAgencyCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Location_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_MagnetSpecialProgramEmphasisSchoolDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_MediumOfInstructionDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_MethodCreditEarnedDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_MigrantEducationProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_MonitoredDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_NeglectedOrDelinquentProgramDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_NeglectedOrDelinquentProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_NetworkPurposeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ObjectiveAssessment_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_OldEthnicityDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_OpenStaffPosition_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_OperationalStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_OtherNameTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Parent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ParticipationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ParticipationStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Payroll_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PerformanceBaseConversionDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PerformanceLevelDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PersonalInformationVerificationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PlatformTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PopulationServedDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PostingResultDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PostSecondaryEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PostSecondaryEventCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PostSecondaryInstitution_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PostSecondaryInstitutionLevelDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProficiencyDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Program_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProgramAssignmentDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProgramCharacteristicDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProgramSponsorDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProgramTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProgressDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProgressLevelDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProviderCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProviderProfitabilityDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ProviderStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_PublicationStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_RaceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ReasonExitedDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ReasonNotTestedDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_RecognitionTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_RelationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_RepeatIdentifierDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ReportCard_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ReporterDescriptionDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ResidencyStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ResponseIndicatorDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ResponsibilityDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_RestraintEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_RestraintEventReasonDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ResultDatatypeTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_RetestIndicatorDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_School_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SchoolCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SchoolChoiceImplementStatusDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SchoolFoodServiceProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SchoolTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Section_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SectionAttendanceTakenEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SectionCharacteristicDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SeparationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SeparationReasonDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_ServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Session_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SexDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SpecialEducationProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_SpecialEducationSettingDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Staff_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffAbsenceEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffClassificationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffCohortAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffDisciplineIncidentAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffEducationOrganizationAssignmentAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffEducationOrganizationContactAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffEducationOrganizationEmploymentAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffIdentificationSystemDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffLeave_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffLeaveEventCategoryDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffSchoolAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StaffSectionAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StateAbbreviationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StateEducationAgency_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_Student_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentAcademicRecord_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentAssessment_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentCharacteristicDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentCohortAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentCompetencyObjective_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentCTEProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentDisciplineIncidentAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentEducationOrganizationAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentEducationOrganizationResponsibilityAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentGradebookEntry_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentHomelessProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentIdentificationSystemDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentInterventionAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentInterventionAttendanceEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentLanguageInstructionProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentLearningObjective_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentMigrantEducationProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentNeglectedOrDelinquentProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentParentAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentParticipationCodeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentProgramAttendanceEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentSchoolAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentSchoolAttendanceEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentSchoolFoodServiceProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentSectionAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentSectionAttendanceEvent_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentSpecialEducationProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_StudentTitleIPartAProgramAssociation_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TeachingCredentialBasisDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TeachingCredentialDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TechnicalSkillsAssessmentDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TelephoneNumberTypeDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TermDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TitleIPartAParticipantDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TitleIPartAProgramServiceDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TitleIPartASchoolDesignationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_TribalAffiliationDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_VisaDescriptor_TrackedDelete;
GO

ALTER SCHEMA tracked_deletes_edfi TRANSFER changes.edfi_WeaponDescriptor_TrackedDelete;
GO
