-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 

COMMENT ON COLUMN edfi.coursetranscript.assigningorganizationidentificationcode
    IS 'The organization code or name assigning the course identification code.';

COMMENT ON COLUMN edfi.coursetranscript.coursecatalogurl
    IS 'The URL for the course catalog that defines the course identification code.';

ALTER TABLE edfi.coursetranscript
    ADD COLUMN externaleducationorganizationnameofinstitution character varying(75) COLLATE pg_catalog."default";

COMMENT ON COLUMN edfi.coursetranscript.externaleducationorganizationnameofinstitution
    IS 'Name of the external institution where the student completed the course; to be used only when the reference ExternalEducationOrganization is not available.';
